export const USER_ROLES = {
  ADMINISTRATOR: "Administrator",
  RECRUITER: "Recruiter",
  TECHNICAL_EVALUATOR: "Technical Evaluator",
};

export const ROLE_BADGE_VARIANTS = {
  [USER_ROLES.ADMINISTRATOR]: "default",
  [USER_ROLES.RECRUITER]: "secondary",
  [USER_ROLES.TECHNICAL_EVALUATOR]: "outline",
};

export const ROLE_GROUPS = {
  DASHBOARD_ACCESS: [USER_ROLES.ADMINISTRATOR, USER_ROLES.RECRUITER],
  ADMIN_ONLY: [USER_ROLES.ADMINISTRATOR],
};
